export { default as Avatar } from './Avatar'
export { default as Background } from './Background'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Navbar } from './Navbar'
